###
GET http://localhost:13000/setup

###
GET http://localhost:13000

###
POST http://localhost:13000/
Content-Type: application/json

{
  "type": "temperature",
  "value": 25.5,
  "timestamp": "2024-09-22T12:00:00Z",
  "userId": 1
}

###
POST http://localhost:13000/users
Content-Type: application/json

{
  "username": "user1"
}

###
DELETE http://localhost:13000/users/3

###
DELETE http://localhost:13000/reset

###
DELETE http://localhost:13000/erase